# 塔罗牌插件配置文件

[plugin]
name = "tarots_plugin"
version = "0.4.0"
enabled = true
description = "塔罗牌插件"

# 组件启用控制
[components]
enable_tarots = true

# 日志配置
[logging]
level = "INFO"
prefix = "[Tarots]" 